version: '2'

services:
  auto-tests:
    container_name: "automated-test"
    build:
      context: .
      args:
        HTTP_CREDENTIALS_USERNAME: ${HTTP_CREDENTIALS_USERNAME}
        HTTP_CREDENTIALS_PASSWORD: ${HTTP_CREDENTIALS_PASSWORD}

#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example
