name: "Automated tests"
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to tests repository"
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          ref: ${{github.ref}}
      - name: "copy environment variables"
        run: |
          cp '.env.example.stage' '.env'
      - name: "Run tests"
        run: |
          HTTP_CREDENTIALS_USERNAME=${{secrets.HTTP_CREDENTIALS_USERNAME}} HTTP_CREDENTIALS_PASSWORD=${{secrets.HTTP_CREDENTIALS_PASSWORD}} docker-compose up --exit-code-from auto-tests
      - name: "Upload artifacts"
        if: failure()
        uses: actions/checkout@v3
        with:
          name: test-report
          path: playwright-report/

      
